ember-m3/ember-m3

.travis.yml, config/ember-try.js
It is definitely possible to make these work if someone ultimately needs the support, but lets remove it for now.
=> Drop support for Ember < 2.12.

addon/initializers/m3-store.js, addon/query-cache.js, tests/unit/initializers/m3-store-test.js, tests/unit/query-cache-test.js
@hjdivad @stefanpenner @rwjblue
This PR adds `unloadURL` and `contains` methods to the queryCache to enable unloading of cached queries.
=> Adding unloadUrl and contains methods to the queryCache

package.json
This partially addresses #18 but we should add a build-time assertion to make sure we're monkeypatching something we're good with, while working on making this use public API.
=> Move ember-data to peerdep.

package.json
Supersede #17.
We don't actually use bower, it's just a holdover from the blueprint.
=> Drop bower dependency

.travis.yml, config/ember-try.js
Leave it only for ember-canary, although obviously it would be better to
drop it there too.
=> Drop use of bower (mostly) in ember-try

addon/initializers/m3-store.js, addon/model.js, addon/schema-manager.js, addon/util.js, tests/unit/projection-test.js, tests/unit/util-test.js
- Implement a crude merge strategy. For simplicity and performance, the strategy will produce special changed keys format, where nested keys are represented as arrays, where the first entry is the name of the key in the parent object and the rest are the keys changed in the nested object.
The `_didReceiveNestedProperties` will skip on detecting changes if the keys have been passed.
- Remove the `@` base model as it is no longer needed. This required adjusting the payloads a little, because I think they no longer require `projectionTypes` in meta (it doesn't bring any value). The most we may need there is a flag to not mark the model as loaded.
- Remove `pushInternalModel` hook which caused two tests to be skipped (`findRecord` and `peekRecord` one). The removal of the hook also required …
=> Final experiments

addon/model.js, addon/util.js, tests/unit/model-test.js, tests/unit/projection-test.js, tests/unit/query-cache-test.js, tests/unit/util-test.js
The migration is not ready yet, there are still some tests failing mainly for cases, which change the type of properties (primitive -> model, model -> primitive) etc.
But I've adjusted the existing tests for detecting deleted properties and split them in tests for validating omitted properties do not trigger changes and nulled properties trigger changes. These are worth reviewing.
=> Migrate to merge strategy from overwrite strategy

addon/model.js, tests/unit/model-test.js
The `isDirty` property doesn't actually exist in the `DS.Model`. The closest there is `dirtyType`. We should either fix it or drop it completely.
=> Fix the `isDirty` property

addon/model.js
There's still a single object, but the functions are on a prototype now
instead of a pojo.
Fix #32
=> Move YesManAttributes functions

addon/initializers/m3-store.js, addon/schema-manager.js, tests/unit/projection-test.js, tests/unit/schema-manager-test.js
Also required altering our `store.preloadData` implementation as it surfaced an issue with property-notification for already populated models. It is now more similar to `store._load` but keeps the record in the EmptyState and skips notifying the record-array-manager if it truly is a "preload" and not an update. cc @igorT
=> Cleanup tests and SchemaManager based on code-review

addon/model.js, addon/util.js, tests/unit/util-test.js
This addresses some of the feedback from PR #38 
- Grouped the projection related properties in the `init` function.
- Converted `_internalModel` to be a getter, which always delegates to the `baseModel`.
- Cleaned up the `merge` function and removed the check for `Date` in the `isObject` function.
- Removed the `modelIsProjection` function from the `SchemaManager`
=> [Projection Support] Addressing some feedback from PR #38

tests/unit/projection-test.js
Here are is an expansion of the two unload tests we had. Hopefully I stayed `true` to the spirit of the test structure.
Only real question is how much we want to test that unloading a related record didn't destroy internal structures, which a live record might need.
Depending on our implementation we may need a test to confirm that the underlying structure has been cleaned up of references once the final projection has been unloaded, but without an actual implementation, I don't think it is possible to write a test for it.
=> [Projection Support] Unload tests

addon/model.js, tests/test-helper.js, tests/unit/model-test.js
As discussed OOB with @hjdivad, this PR asserts that you cannot `model.set('id', '1')`.
For client-side creation with ID, ID must be passed in via `store.createRecord('foo', { id: '1' });`
cc @dnachev
=> [FEAT] disallow late ID setting

tests/unit/projection-test.js
A starting point for the write cases discussion. I think writing projection is not as straight-forward, I expect to have some healthy discussion here.
The current thought process was the following:
- projections without IDs are not linked in any way, e.g. you can create as many as you want and modify as much as you want
- created projections with IDs are immediately linked, e.g. they represent the same underlying entity, even though this entity doesn't exist on the server
- saving a new projection record can create an entity on the server and the projection will be correctly setup to be updated by future fetches
- changing a projection dirties all associated entities (if they contain the attribute; note - the test needs to be enhanced to cover non-whitelisted properties)
- saving a …
=> [Projection Support] Write Tests

tests/unit/projection-test.js
@runspired As discussed over Slack, this is a test to validate we correctly handle record arrays retrieved from attribute array reference property.
=> [Projection Support] Add unload test for record arrays

addon/initializers/m3-store.js, addon/model-data.js, addon/model.js, tests/unit/projection-test.js
The changes are somewhat disconnected, here is an overview:
- `preloadData` monkey patch to enable us to put a base record data without marking as loaded
- Linking a projection model data to a base model data (no support for save yet)
- Some small changes here and there like relying on `setAttr` instead of assigning directly
- Unskipping relevant tests, which are now passing against Igor's Ember Data branch
=> [Projection Support] Initial work for cache consistency and property invalidation

addon/model.js, tests/unit/model-test.js
It's a bit strange to do so, but it's not actually an issue as it is for top-level models.
=> Allow id mutation in nested models

README.md, addon/model.js, addon/schema-manager.js, blueprints/schema-initializer/files/app/initializers/schema-initializer.js, tests/unit/model-test.js
passing _data object to schema.js, in order to check the key and value and compute attribute reference.
=> passing _data object to schema.js

package.json
ember-source should only be a dev dependency here (and possibly a peer dependency also, though I didn't introduce that as I wasn't sure we needed it to be explicit).
=> Remove direct dependency on ember-source.

README.md
Added paragraph detailing the interaction between the cache entries stored by entity id vs cacheKey
=> Update README.md to clarify `cacheKey`'s caching behavior

.travis.yml, addon/record-array.js
Previously we fired array change events on the proxy itself.  This is incompatible with the changes in https://github.com/emberjs/ember.js/pull/16166 which depend on the events firing on the underlying content.
=> Fire array change events on content

.eslintrc.js, addon/initializers/m3-store.js, addon/model.js, addon/query-cache.js, addon/util.js, package.json, tests/dummy/app/app.js, tests/dummy/app/helpers/month-of.js, tests/dummy/app/router.js, tests/dummy/app/routes/alt.js, tests/dummy/app/routes/index.js, tests/helpers/destroy-app.js, tests/helpers/module-for-acceptance.js, tests/helpers/start-app.js, tests/unit/initializers/m3-store-test.js, tests/unit/model-test.js, tests/unit/query-cache-test.js, tests/unit/store-test.js
This deals with deprecations, but it doesn't handle the failures which stem from the state CPs not being treated as descriptors during dependent notifications stemming from `currentState` change events (thanks for digging into this @dnachev).
Not yet clear whether or not those errors require changing the way the CPs are defined or if this is a regression in ES5_GETTERS.
=> clean up some beta issues

addon/query-cache.js, tests/unit/query-cache-test.js
Updated queryURL logic to use query cache for storing promise information for same cacheKey and upon multiple ajax invocation that promise is returned until promise is fulfilled.
=> Updated queryURL logic to use query cache for storing promise for cacheKey

addon/model.js
ember-m3 doesn't officially support phantomjs but we won't use native
Map for now.
=> Use @ember/map instead of native Map

addon/model-data.js, tests/unit/model-data-test.js
Since `dirtyKeys` is initialized as `undefined`, we want to guard against calling `_notifyProperties` with `undefined`.
=> [BUGFIX] Ensure `notifyProperties` does not get called with undefined

addon/model-data.js, addon/model.js, tests/unit/model-data-test.js, tests/unit/model-test.js, tests/unit/projection-test.js
When we `set` on a projection, we delegate to the base always, but the change event was not propagated to all projections.
This PR adds this (essentially moving the `notifyPropertyChange()` call to the `setAttr()`). It has the side effect, because it will use the `storeWrapper.notifyPropertyChange()` call, which requires to be run in a runloop causing many of the existing tests to be changed slightly.
=> Correctly notifying all projections on `set`

addon/model-data.js, tests/unit/model-data-test.js, tests/unit/projection-test.js
This is a rebase of the #62 PR.
The implementation is little crude, because it avoids using `clientId` to connect to the base ModelData immediately after the record is created. Instead it delays until the record is committed.
The refactoring to use `clientId` will come in a separate PR, because it is dependent on fixes in Ember Data.
=> Projections unload and save 

README.md, addon/model.js, addon/record-array.js, addon/schema-manager.js, blueprints/schema-initializer/files/app/initializers/schema-initializer.js, tests/dummy/app/initializers/schema-initializer.js, tests/unit/initializers/m3-store-test.js, tests/unit/model-test.js, tests/unit/projection-test.js, tests/unit/query-cache-test.js, yarn.lock
Given an array of references, we were relying an `isAttributeArrayRefernce` to compute whether or not we  return a `RecordArray`. Clients will be confused when the UI does not get
updated even if they did not implement the API correctly.
In order to make m3 more ergonomic, we will consistently return `RecordArray`.
- Remove `isAttributeArrayReference` and let the schema handle the logic of
returning proper data within `computeAttributeReference`.
- `computeAttributeReference` now has to take care of _either_ an array of
references or a single reference. We will check it's type with
`Array.isArray`, and wrap it with `RecordArray` accordingly.
- Refactored some of the methods to take in reference rather than many
params (store, schema, etc) to ease code readability.
=> [BUGFIX] Ensure array of references are wrapped with RecordArray

addon/model-data.js, package.json, tests/unit/model-data-test.js, yarn.lock
This is a refactoring on top #106 PR and it relies on two Ember Data fixes:
- `StoreWrapperAPI` must have a function to set server-side ID for the model data. This is because, when we save a projection, we receive the server-side ID through the projection model data instead of the base model data.
- `Store.updateId()` should remove the model data from the `_newlyCreated` hash, which is used for tracking client-only records
- `_newlyCreated` hash must be split by model name, because the projection model data and the base model data should use the same `clientId` for simplicity reasons.
The above fixes are just suggestions. Open to suggestions.
=> Refactor to use clientId if id is missing

addon/query-cache.js, tests/unit/query-cache-test.js
An attempt at `queryURL` hook for the adapter, which gives slightly more flexibility in how queries against an URL are handled with the following signature:
`queryURL(url, method, options)`
where `options` is a subset of the options passed in to the `queryURL` function itself. Right now, only `params` are propagated, but in future, options the adapter might be interested in can be added.
I specifically avoided just passing the options, which are passed to `ajax()` as they are tight to jQuery and I don't think we should tie the API of this hook to something, which is being removed from Ember.
The other decision was the automatic fallback to the `ajax` in case the adapter does not implement the hook. Because all of the functionality can work without the adapter having to implement anything …
=> `queryURL` Adapter Hook

CHANGELOG.md, addon/model-data.js, addon/model.js, addon/record-array.js, tests/unit/model-test.js
Values that are set on the model directly (as opposed to ones that come from the
server payload) are treated as resolved.  This means that they do not go
through hooks like `schema.computeAttributeReference` for arrays of
references.
This also fixes a bug where setting an already-resolved `RecordArray`
would fail to update the `RecordArray` in-place if the new value was a
`RecordArray` of models (rather than a plain array of models).
=> Do not resolve values from `setUnknownProperty`

addon/model-data.js, addon/model.js, tests/unit/model-test.js, tests/unit/projection-test.js
There were two cases, where the schema had to do its own normalization (using `dasherize`) of the model names:
- Resolving a record array of references - M3 uses the internal `_internalModelForId` function, which expects a normalized model name. There is a small improvement to be made here to use `hasRecordForId` before trying to get the internal model as to not create an empty internal model if the reference is bad, but this is for another PR.
- Resolving base model data - `modelDataFor()` does not normalize the input, before creating the internal model, tracking the model data. This should probably be fixed in Ember Data itself, putting it here for illustration purposes.
=> Model Name normalizations

addon/model-data.js, tests/unit/projection-test.js, yarn.lock
The `changedAttributes()` did not delegate to the base model data, when appropriate leading to a bug where:
```javascript
projection.set('property', newValue);
projection.changedAttributes() // == {}
```
Open question: ideally, we should filter out the `changedAttributes()` result based on the attribute whitelist from the schema, the question is where it is more appropriate to do - in the `model-data` or in the `model`? I think it is easier to be done in `model-data` as the code already iterates over the nested model datas.
=> Fix `changedAttributes` for projections

addon/model.js, tests/unit/model-test.js
Despite the fact we were passing `schemaInterface` to the `computeNestedModel`, it wasn't correctly set, which caused an exception to be thrown.
Added a test for it as well.
=> Fix `computeNestedModel` access to schemaInterface

addon/record-array.js, tests/unit/model-test.js, tests/unit/query-cache-test.js
`RecordArray`s created for either `queryURL` or reference arrays
register themselves with `internalModel`s so that they'll automatically
update when those models are unloaded.
Now, register with models that are added to these arrays so that they
also share this functionality.
=> Associate newly added records to record arrays

addon/initializers/m3-store.js, addon/m3-reference-array.js, addon/m3-tracked-array.js, addon/model-data.js, addon/model.js, addon/record-array.js, addon/resolve-attribute-util.js, package.json, tests/unit/model/dependent-keys-test.js, tests/unit/model/tracked-array-test.js
In general this is not recommended, but it can help if it's difficult to determine whether the server payload should be interpreted as a tracked array or a record array (ie whether it's an array of nested models or a reference array).  If this is a problem it is most likely a problem for empty arrays.
Associating resolved values with tracked arrays means that in the tracked array case new records that are added will be removed when they're unloaded.
=> Associate resolved values with tracked arrays

package.json, yarn.lock
The modelFactoryFor -> _modelFactoryFor changes slated for 3.3.0 ended
up getting released in 3.4.0.  This commit updates the devDependency to
reflect that.
=> Fix Ember Data dependency

addon/model.js, tests/unit/model/state-test.js
Although initial values were computed from the top model, the computed property cache would not be properly invalidated when the top model's state changed.  Also the state changes of nested models would not be reflected in the top model.
=> Keep nested model dirty state in sync.

addon/record-data.js, addon/utils/copy.js, tests/unit/utils/copy-test.js
Use this instead of ember's deprecated copy.  It's slightly tweaked to
1. ignore Copyable and
2. always be deep copy
Chief motivation is to remove the warnings
=> Copy deepcopy from Ember

addon/record-data.js, tests/unit/projection-test.js, tests/unit/record-data-test.js
Calling rollbackAttributes on a record data that has a base record data
was not working properly because the attributes mutated were in
the record data from the projection and not the base record data.
When dealing with projections all the interactions should be delegated
to the base record data.
In this PR I am adding a fix to call rollback attributes on the base
record data when one is present.
While adding a test for this I noticed that a similar bug was present in `isAttrDirty` which I've also addressed.
=> Fixes rollbackAttributes for record data from projections

addon/record-data.js, tests/unit/model/changed-attrs-test.js, tests/unit/record-data-test.js
Was able to reproduce a scenario where if you change a nested model and called save(), the changed attributes actually persist instead of being reset, so this new test will fail.
Investigation: Inside `willCommit`, we have `childRecordData.willCommit()` which never got called because childRecordData is an array of 2 elements, ~~which I think holds the old and new record.However, I'm not sure if the isArray check there is intentional for this scenario.~~ `DidCommit` only gets called once for the top-level model and the `_mergeUpdates()` call never happens.
Theoretically the test name above this new test was a bit misleading because it didn't actually test the changedAttribute() behavior at all.
=> Fixing nested model updates from local updates and partial updates from server.

addon/record-data.js, tests/unit/projection-test.js, tests/unit/record-data-test.js
`hasLocalAttr` was not previously delegating to the base record data when
checking the attributes. This introduced problems with projections
because all mutations happen on the underlying base record so when cheking
for the existance of an attribute on a projection the result was always false. 
As part of the fix we now delegate to the base record `hasLocalAttr`
method when present.
=> hasLocaltAttr now delegates to base record

addon/record-data.js, addon/utils/copy.js, tests/unit/utils/copy-test.js
1. cycle detection was broken
2. it's not a generic copy utility: we don't need or want to copy
non-JSON values which will sometimes appear in `attributes`.
It's perfectly fine for such values to be in `attributes` as they will
likely have serialization paths in users' serializers (eg if they are
models), but there is no need to copy such values when calculating
changed attributes.
=> Fix issues in deep copy

addon/record-data.js, tests/unit/model/projections/changed-attrs-test.js, tests/unit/record-data-test.js
This function worked as expected for non-projections, but projections failed to delegate to their base record data, resulting in invalid state that among other things caused `changedAttributes` to be wrong in some cases.
[Fix #248]
=> Delegate `_destroyChildRecordData` to base

addon/resolve-attribute-util.js, addon/services/m3-schema.js, tests/dummy/app/services/m3-schema.js, tests/unit/model/changed-attrs-test.js, tests/unit/model/projections/changed-attrs-test.js
Previously if an array was not a reference array we did not give users a chance to handle it in-bulk vs by individual member. This makes extraction of some forms of schema information that needs to be either index-aware or aware that it is within a collection of some form difficult to detect. This change allows users to handle.
BREAKING: This change will break users who currently check for `value` in `computeNestedModel` being of type `object` but do not check whether it is an `Array`. The refactor is tiny, with the simplest refactor being to return `null` directly to maintain previous behavior.
e.g.
```js
computeNestedModel(key, value) {
if (Array.isArray(value)) { return null; }
// continue on ..
}
```
=> feat: enable computeNestedModel to handle arrays

addon/m3-tracked-array.js, addon/resolve-attribute-util.js
I noticed lots of failures due to trying to access `.value` in v-web when testing my recent change, so figured it best to bring this back with a deprecation.
=> fix: bring back M3TrackedArray.value and deprecate

.travis.yml, tests/unit/query-array-test.js, yarn.lock
This is a weird failure though since it should only be affecting the
floating deps stage on travis, but we're seeing these failures on all
the stages.
=> fix: lint issues from prettier

addon/query-cache.js, tests/unit/query-cache-test.js
This PR addresses the issue described in https://github.com/hjdivad/ember-m3/issues/280, where promises fulfilling with an error response are still cached by queryURL. This results in the undesired behavior that subsequent identical requests after a first failure are automatically rejected, thus preventing retries.
=> Evict Promise cache for rejected responses to queryURL

addon/model.js, yarn.lock
Ran `yarn upgrade` and fixed prettier style issues from upwards drift of prettier to `1.18` from `1.17`
=> chore: yarn upgrade dependencies

.eslintignore, addon/m3-reference-array.js, addon/model.js, addon/query-cache.js, addon/record-array.js, addon/resolve-attribute-util.js, addon/utils/notify-changes.js, tests/integration/chain-watchers-test.js, tests/integration/reference-array-test.js, tests/unit/record-array-test.js, tests/unit/utils/notify-changes-test.js
Previously only property changes were batched; now array changes in
record arrays are also batched.  Note that this is not the case for
tracked arrays, but this feature should be added there as well.
As part of this change, remove `ArrayProxy` as the base class of
`RecordArray`.  Although our arrays are array proxies, the base class is
not adding value and it's easier to implement all of the logic
ourselves.
=> feat: batch array changes

addon/record-array.js
We don't extend ArrayProxy any longer so don't need the setter.  Also
with the earlier changes we can simplify the getter.
=> chore: clean up RecordArray.length

config/ember-try.js
Ember try configuration was broken by Ember Data's packages switch.
This commit updates to use npm release tags instead of git branches.
=> chore: update embery try

addon/record-array.js, tests/integration/reference-array-test.js
RecordArray now triggers change events on unloadRecord.  Previously we
relied on `ArrayProxy` to implicitly trigger change events during
`removeObjects`.
Also trigger change events for `length` which was similarly handled by
`ArrayProxy`.
=> fix: trigger property change events

tests/unit/store/global-cache-test.js
=> fix: drop use of `_map` in tests

addon/initializers/m3-store.js, package.json, tests/unit/model-test.js, tests/unit/store/global-cache-test.js, yarn.lock
This is used to clean up our secondary cache.
Note that the new (and prior) monkeymatching is undesired as it's using
private API in both cases, and `_internalModelsFor` is slated to be
removed as private API (not intimate).
The public API that enables this kind of secondary cache should be used
when we switch to the custom model class API (see #294).
[fix #342]
=> fix: fix hook for `internalModel` removal

addon/record-data.js, tests/unit/record-data-test.js
M3 was relying on an unknown implicit behavior to create new client side records without using createRecord. This broke when `clientId` began to be unique across types. This change prepares M3 for versions of EmberData where `clientId` is unique across types when paired with https://github.com/emberjs/data/pull/6334
=> fix: base RecordData creation when creating a projection

addon/resolve-attribute-util.js, tests/unit/model/references-test.js
1. Allow user schemas to compute references with `null` ids and given
types (which will result in `null` results)
2. Prioritize the user schema's `computeAttributeReference` over the raw
value when deciding whether to build a reference array.
=> fix: a couple of bugs with references

addon/record-array.js, tests/test-helper.js, tests/unit/query-cache-test.js, tests/unit/record-array-test.js
Previously `replace` did not pass the index to array observers
correctly.
Also enable `setupTestIsolationValidation`.
Co-authored-by: Robert Jackson <rjackson@linkedin.com>
=> fix: arrayDidChange called with correct args

.commitlintrc.js
Most of the rules I don't actually like.  The only ones I really want to
enforce are the ones that are relevant to standard git tools and impact
the way eg `git log` formats messages.
=> chore: Remove extra commitlint rules

addon/model.js, addon/record-data.js, tests/unit/model/dirty-test.js, tests/unit/record-data-test.js
Previously `model.set(attr, val)` would only dirty if the schema dirtied
specifically `attr`.  Now, the model will be dirtied if the schema
dirties *any* attribute during a set.
=> fix: issues with dirty checking

README.md, addon/initializers/m3-store.js, addon/query-cache.js, tests/unit/query-cache-test.js
I've added support for `adapterOptions`, custom options that can be passed along to the adapter, to the `queryURL` method. This matches the behavior of other Ember Store methods, like the ones provided by the REST adapter.
=> Add support for adapterOptions to queryURL

.travis.yml, README.md, config/ember-try.js
- Fail the build on beta channel regressions
- Update README to clarify support policy now that we are less dependent
on private Ember Data API
=> chore: update travis.yml

index.js
Using a mutable object on the addon's prototype causes issues when ember-m3 is consumed by an addon as a direct dependency.
The specific setup is:
* `ember-m3` depends on ember-compatibility-helpers
* `ember-m3` has the following in its `index.js`:
```js
module.exports = {
name: require('./package').name,
options: {
m3: true,
babel: {
loose: true,
},
},
};
```
* addon B depends on `ember-m3` (**not** a dev dep)
In this scenario, `ember-m3` will be instantiated twice. Once for addon B's dummy app and again for addon B's direct dependency. Since `ember-m3` had a _mutable object_ on its prototype (yes, you know whats coming now) ember-compatibility-helpers adds a `plugins` array to it and pushes into it.
Now that ember-m3 has updated to Babel 7, pushing the same babel plugin into the plugins …
=> Do not put mutable state on the prototype.

addon/adapters/debug-adapter.js
don't rely on EmberData's injection of store into data-adapter:main
=> fix: inject store service

addon/adapters/interop-debug-adapter.js, addon/adapters/m3-debug-adapter.js, addon/index.js, addon/initializers/m3-store.js, app/adapters/debug-adapter.js, tests/integration/interop-debug-adapter-test.js, tests/integration/m3-debug-adapter-test.js
This PR will allow both `DS` models and `m3` models to render and be tracked in `Ember Inspector`, which will help developers as they migrate onto `m3`.
=> feat: interoperability between Ember Data and m3 in debug-adapter

addon/query-cache.js, tests/unit/query-cache-test.js
According to the m3 docs, it looks like currently in order to set custom headers, we have to reference the -ember-m3 adapter directly, it would be nice if we are able to pass the headers through store.queryURL so we can still take advantage of the serializer in queryURL: https://github.com/hjdivad/ember-m3#serializer--adapter
This change allows custom headers to be passed into queryURL. @runspired @hjdivad
=> Add headers support for queryURL

addon/adapters/interop-debug-adapter.js, addon/adapters/m3-debug-adapter.js, tests/acceptance/m3-test.js, tests/dummy/config/environment.js, tests/integration/interop-debug-adapter-test.js, tests/integration/m3-debug-adapter-test.js, tests/pages/index.js, tests/test-helper.js
Resolves two deprecations that were spewing in the test suite:
1) deprecated test syntax
2) calling store methods after the store has been destroyed
For this latter I discovered we had tests leaking state across other tests, I've updated the test dependent on the leaked state to test a bit closer to what it *thought* it was testing.
=> chore: cleanup deprecations

addon/model.js
Noticed this while implementing some build infra. Currently we greedily create this for every record when it'll only be used for a tiny number. Given the heavy weight of the Errors class I suspect we will see a significant improvement in render times for applications using M3.
=> perf: instantiate errors lazily

index.js
Don't overwrite existing babel plugins in `index.js`
=> Fix issue from #453

index.js
We fell back to a value of `false` which would always strip the code.
This commit changes the fallback to `null` when developing the addon,
which leaves the feature flag a runtime concern.
Also move init code to `included` as `isDevelopingAddon()` is not
reliable in `init`.
=> Fix CUSTOM_MODEL_CLASS fallback

index.js, package.json, yarn.lock
The feature import was based on Ember Data 3.14, which is not the
current canary.
This commit still depends on an unstable import path
`@ember-data/private-build-infra/src/features`.
=> Fix ember data feature import

addon/adapters/m3-debug-adapter.js, tests/integration/interop-debug-adapter-test.js
This fix is similar to this PR in Ember Data: https://github.com/emberjs/data/pull/6549 which ensures that when the inspector is closed and reopened, the adapter correctly rewatches previously added model types.
=> fix: remove seen model types in debug-adapter when inspector is closed

addon/model.js, tests/unit/model/state-test.js
Nested models that have their last changed attribute set to its original
value should not undirty their parents, if those parents have other
dirty attributes.
=> Fix dirty issue

addon/model.js, addon/record-data.js, tests/unit/model/projections/changed-attrs-test.js
https://github.com/hjdivad/ember-m3/pull/377 introduced `hasDirtyAttr()` in order to have better support for state updating when a record has an attribute set.
https://github.com/hjdivad/ember-m3/pull/433 used `hasDirtyAttr()` to check whether to revert the record to a clean state.
However, `hasDirtyAttr` did not account for nestedModels, thus reverting the parentModel to a clean state even when nestedModels had changes.
This commit removves `hasDirtyAttr` and replaces it with existing method `hasChangedAttributes` which already correctly accounts for the childRecordDatas.
=> Fix isDirty check for parents of nested models

addon/record-data.js, tests/unit/record-data-test.js
The accumulation of isDirty when there are multiple arrays of
childRecordDatas was broken.
=> Fix hasChangedAttributes with arrays of nested models

tests/integration/model-invalidation-render-test.js
Adds a test asserting that m3 models do not dirty when setting
properties, which was an issue with ObjectProxy in older versions of
Ember
=> chore: add test for re-render

addon/model.js, tests/unit/model-test.js
The inspector error is no longer thrown when you click on a record.
I'm not that sure if the test setup is ideal though, so would like feedback on that. I also tried to stub out `init` as a no-op, but then I got a `Maximum call stack size exceeded` error as it bounced between getting the `id` and `unknownProperty.` Is there actually I way I can test before `init` is run?
=> Allow .toString to be called on record prototype

app/data-adapter.js, package.json, tests/acceptance/m3-test.js
This is to ensure that the m3 `data-adapter` takes precedence over the Ember data's `@ember-data/debug` adapter so the inspector works as intended.
=> Re-export interop-debug-adapter in app as data-adapter

RELEASE.md, package.json, yarn.lock
Primary changes:
* Leverages `$EDITOR` to allow editing of changelog prior to commiting / publishing to GitHub release.
* Ensures the same GitHub token is used between lerna-changelog and release-it.
* Update dependencies (resolves a few `npm audit` related issues).
Related changes (for further reading):
* https://github.com/rwjblue/create-rwjblue-release-it-setup/releases/tag/v2.0.0
* https://github.com/rwjblue/release-it-lerna-changelog/releases/tag/v2.0.0
* https://github.com/rwjblue/release-it-lerna-changelog#launcheditor
Closes https://github.com/hjdivad/ember-m3/pull/594.
=> Update automated release setup.

.github/workflows/nightly.yml
cron * 14 means every minute of the 14th hour.  GitHub Actions will
limit this to the minimum of every 5 minutes, although it didn't
actually run 12 times presumably because of the length of the jobs
themselves.
Fix the cron schedule so the job only runs once per night.
=> Fix nightly run

testem.js
Some CI systems seem to hit the default limit much more often than others. Specifically, GitHub actions seems to fail fairly consistently (5 out of 10 job runs) without increasing the timeout, but passes consistently with an increased limit.
This matches the change made in the default blueprint https://github.com/ember-cli/ember-cli/pull/8986
=> Increase browser start timeout

addon/mixins/store.js
* Avoid creating a closure within `_pushInternalModel` (use a single
shared monkey patch function)
* Do not cleanup the monkey patch (the changes are inert, and safe)
=> Refactor memory related monkey patch fix.

addon/mixins/store.js
When there are multiple requests in parallel in fastboot, using an instance level check for guarding the proto modifications does not work, as each instance of the store will modify the globally shared class prototype, and stash the previously modified one. The stashed methods end up creating a chain leading to a memory leak.
=> Fix memory leak in fastboot caused by modifying class prototype

package.json, yarn.lock
https://github.com/hjdivad/ember-m3/pull/651 pinned the `ember-source` version to 3.16.5, but _should_ have set it to `^3.16.5` (or 3.16.6 which is also released at this point).
We should **not** pin exact dependencies in `package.json` (especially for packages that follow SemVer), that is what lock files are for.
/cc @igorT
=> Unpin `ember-source` version in `package.json`

.github/workflows/ci.yml, README.md, addon/-infra/potential-packages.js, addon/-infra/versions.js, addon/-private.js, addon/initializers/m3-store.js, addon/m3-tracked-array.js, addon/mixins/store.js, addon/model.js, addon/record-array.js, addon/record-data.js, addon/resolve-attribute-util.js, addon/services/store.js, config/ember-try.js, package.json, src/debug-macros.js, tests/interop/model-test.js, tests/unit/model-test.js, yarn.lock
This will be a major version bump (2.0.0)
This aims to drop unused branching, improving hygiene and reducing complexity.
=> Dropping support for < ember-data 3.12

addon/m3-tracked-array.js
_removeInternalModels loop had a off by one error that was hidden by a
superfluous call to `isResolvedValue`.
`isResolvedValue` is pointless in this place, as in a tracked array
all of the models are always resolved
=> cleanup: Fix array iteration off by one

addon/m3-tracked-array.js
This makes the PRs for unifying array handling much easier to read,
as they will only apply to the feature flagged cases
=> [cleanup] Split feature flagged tracked arrays into two classes

.github/workflows/ci.yml
Node 13 was EOL at the end of May this year. This doesn’t really change anything regarding our supported Node’s, but it ensures that CI is running on the platforms we support.
https://nodejs.org/en/about/releases/
=> ci: Drop Node 13 and add Node 14

index.js
When the project depends on a recent enough version of `ember-data` meta package we do not need to check for the individual packages themselves (they are handled by the meta package).
When `ember-cli-version-checker`'s `check()` API is used in an application with a massive number of addons (> 100,000), it takes a massive amount of time to run. This avoids that specific issue (while we work through the algorithmic issues there) by avoiding the check in the simple case where the project has a direct dependency on `ember-data`.
=> Avoid `checker.check` when project depends on ember-data

index.js
backport #836 
The original code was written to validate that the project has the required dependencies inside the `included` hook. This works perfectly fine and is _not_ overly slow (takes ~500ms in a **massive** application). This `included` hook is called once for every `ember-m3` addon instance in the addon graph.
Unfortunately, in some applications you may have a shared `data-layer` package that depends on `ember-m3`, and that `data-layer` package is depended on hundreds of other dependencies. In that scenario, the 500ms cost is multiplied by each `ember-m3` instance which results in a much larger overall cost (~ 200s).
The good news is that this is **very easy** for us to resolve! We are already checking the global project instance (which is the same across all of the `ember-m3` …
=> Avoid checking project dependencies more than once per project

addon/query-cache.js, addon/services/store.js, tests/unit/record-data-test.js
AFAICT `new Object(null)` is no different than `new Object` which is no different from `{}`, but in these cases we _actually_ want an empty dictionary (without prototype pollution).
=> Replace `new Object(null)` with `Object.create(null)`.

addon/query-cache.js, tests/unit/query-cache-test.js
Previously queryURL would only be able to resolve
1) Ember Data compatible JSON:API documents and
2) null or undefined
[fix #750]
=> queryURL can resolve primitive values

addon/record-data.js, tests/unit/projection-test.js
If you removed a record from an array of nested records, we did not update the baseRecordData, which thus kept the original nested childRecordData. If you then pushed a new object in, it would merge the new object with the previously removed data, leading to incorrect results.
It seems very likely that there are other issues with childRecordData projection syncing, that we should investigate.
=> Fix keeping embedded records in sync inside projections

addon/adapters/m3-debug-adapter.js
Temporary fix for #807 
The bug happens when iterating over _recordValues and find a reference to another [_MegamorphicModel_](https://github.com/hjdivad/ember-m3/blob/971f3764b1aa7121e34ade4df82eaea8026d8b75/addon/adapters/m3-debug-adapter.js#L55)... 
`record.debugJSON()` returns the `recordData`'s, `_data`, the last known data from the server inside `recordData._data`... so it returns the [reference](https://github.com/hjdivad/ember-m3/blob/971f3764b1aa7121e34ade4df82eaea8026d8b75/addon/record-data.js#L923) and [this method](https://github.com/hjdivad/ember-m3/blob/971f3764b1aa7121e34ade4df82eaea8026d8b75/addon/adapters/m3-debug-adapter.js#L35) is modifying the reference, which leads to this bug... this is _always_ happens, and leads to other kind of more "serious" bugs like …
=> temporary stringify fix

addon/adapters/interop-debug-adapter.js
This should fix the recent failures on canary, which are due
to the M3DebugAdapter now eagerly looking up injections.
Fixes #1001
=> Pass owner when creating M3DebugAdapter

.github/workflows/ci.yml, addon/-infra/features.js, addon/base-record-array.js, addon/model.js, index.js, package.json, src/debug-macros.js, src/postpublish.js, src/prepublish.js, tests/index.html, tests/test-helper.js
Adds support for wrapping M3 models and arrays in a native Proxy,
allowing them to be accessed using Plain JS (tm) syntax. This is still
a work in progress as some functionality, such as `Array.isArray`, does
not work on the arrays, and additionally it is double wrapping
everything with Ember's own proxy system so it is very expensive
overall to enable perf-wise. As such, it is kept behind a feature flag
that can only be enabled in canary builds.
=> Adds support for native Proxy behind a canary feature flag

addon/record-data.js, tests/unit/record-data-test.js
Hello, I just noticed something I consider a bug, but not sure if it's actually a bug, or intended.
When `MegamorphicModel.eachAttribute` is called, the callback is executed more than once per `key` if its on multiple "buckets" i.e. `this._attributes` and `this._data`
=> only execute callback once per key for eachAttribute

tests/helpers/warning-handler.js, tests/test-helper.js, tests/unit/model-test.js
Ember 3.27+ no longer compiles module imports down to globals, this means that when `import { warn } from '@ember/debug'` you **can no longer** stub `Ember.warn` directly and expect it to intercept the warning.
This commit introduces a new API that we can use to intercept warning invocations (leveraging `registerWarnHandler` from Ember itself), as well as ensuring that our own tests never "leak" unhandled warnings (which we didn't have a problem with, but seemed like a nice thing to add :smile:).
Fixes https://github.com/hjdivad/ember-m3/issues/1046
=> Refactor warning capturing and testing.

addon/model.js
without this check and early return we take property codepaths and then blow up in `assertNoChanges` because the keys are never handled.
=> Fix state notifications when CUSTOM_MODEL_CLASS is active

index.js
When running in production, ember-m3 avoids emitting any modules that exit in its `addon/-infra/` and `addon/adapters/` folders.  Unfortunately, we still emit a file into the app tree that attempts to import from `ember-m3/adapters/` due to our `app/data-adapter.js` file which has a simple re-export.
This ensures that the `data-adapters.js` file is not emitted in production builds (so that it does not emit an invalid import).
=> Avoid invalid imports in production app tree

index.js
In some circumstances (e.g. while processing within Embroider's OneShot process, or when ember-m3 is a dependency of another addon) our `included` will be called multiple times and attempt to add the babel
plugins to the app each time. This results in the "duplicate preset detected" error from Babel itself.
This patch updates our plugins array mutation code to first check if our plugins have been added before adding them (preventing the error).
=> Ensure we do not add custom babel plugins multiple times

.husky/_/husky.sh, package.json, yarn.lock
It had broken since the upgrade from 4.x to 6.x and left some repos in a
bad state.  It provides no general value; contributors can set up their own
pre-commit hooks if they want, any other checks should be handled via
the CI test jobs (i.e. via yarn test).
=> Remove husky

README.md, addon/model.js, addon/services/m3-schema-manager.js, addon/services/m3-schema.js, tests/unit/model/errors-attribute-test.js, tests/unit/schema-manager-test.js
Adding the ability to configure whether to read from underlying data's `errors` attribute if it exists
=> feat: make errors attribute configurable

m3-perf-testing-app/app/routes/materializing.js, m3-perf-testing-app/testem.js, m3-perf-testing-app/tests/acceptance/materializing-test.js
Running https://github.com/hjdivad/ember-m3/pull/1157 shows that the materialization test is somewhat noisy, increasing the number of iterations to decrease noise
=> Increase iterations in materialization perf test to decrease noise

addon/resolve-attribute-util.js, tests/unit/model/tracked-array-test.js
We discovered instances in the wild of users wrapping models in an ember object proxy and returning those from schema hooks. https://github.com/hjdivad/ember-m3/pull/789 broke some of those use cases, by accessing `_internalModel` in all of the array creation flows, thus triggering Ember's object proxy property access assertion. This is a temporary fix for that behavior, which goes away in the custom model class branch.
=> Allow custom ObjectProxy instances to be wrapped around an M3Model instance 

addon/model.js, config/ember-try.js, package.json, tests/unit/model/state-test.js, yarn.lock
With Custom Model Class, we were notifying property changes for `isDirty`  on embedded models, which normally depend on their parents `isDirty` state, causing a loop.
=> Custom Model Classes: Ensure isDirty for embedded records doesn't recursively loop

addon/resolve-attribute-util.js, tests/unit/model/plain-array-test.js
Previously we did not have test coverage of resolving plain arrays that contain nested objects or references. This PR adds test coverage and fixes a bug where we would not detect nested models or references inside a plain array.
=> Fix plain arrays resolving and add tests

.github/workflows/perf-check.yml, m3-perf-testing-app/app/router.js, m3-perf-testing-app/app/routes/materializing.js, m3-perf-testing-app/tests/acceptance/materializing-test.js
Perf app tests were timing out on CI, as running dev builds on CI containers was too slow, causing testem to time out while the records were being materialized. Now for testing the perf app, we materialize fewer records.
=> Make materializing route in perf app configurable

CHANGELOG.md
Brings the backported changelog from `release/3-0-x` to `master`
=> Add v3.0.8 to Chanelog.md on master

addon/model.js, addon/services/store.js, tests/unit/model/saving-test.js
In CUSTOM_MODEL_CLASS branches, we were not triggering the `isDirty` notification when the record had been saved.
Also, because we rely on object identity of `_topModel`, we need to account for potential proxy values that could be wrapping the Megamorphic model, so now we set '_topModel' after we instantiate the MegamorphicModel instance.
=> Fix isDirty for inflight records and set _topModel to the proxy value

addon/model.js, tests/unit/model/saving-test.js
We can't use the request service to lookup the embedded records. They inherit the saving state of their parent.
=> Fix isSaving for embedded records when CUSTOM MODEL CLASS is on

addon/utils/resolve.js, tests/unit/model/projections/managed-arrays-test.js
This was untested but worked by accident due to how `internalModel` cache worked. Added test coverage and a more robust solution in the Custom Model Classes case
=> Fix for projected models resolving in projected arrays, when CUSTOM_MODEL_CLASS is on

addon/model.js, tests/unit/model/errors-attribute-test.js
Skip the code flow for `_removeError ` if `this._schema.useUnderlyingErrorsValue(this._modelName)` returns true
=> fix: skip this.errors.remove if useUnderlyingErrorsValue

addon/base-record-array.js, addon/model.js, tests/integration/managed-array-tracked-test.js, tests/unit/model/native-access-arrays-test.js
Because ManagedArray is now behind a proxy, it does not pass the internal ember `isEmberArray` check that uses a WeakSet https://github.com/emberjs/ember.js/blob/21bd70c773dcc4bfe4883d7943e8a68d203b5bad/packages/%40ember/-internals/utils/lib/ember-array.ts, so we have to access '[]' when we access ManagedArrays
=> Add support for tracked properties with proxied managed array

addon/record-data.js, tests/unit/model/state-test.js
`isDeleted` state used to be handled by ember-data internal-model, with `3.28` we now need to handle it ourselves
=> Fix isDeleted rollbackAttributes for Custom Model Class

tests/helpers/prop-get.js, tests/unit/model/state-test.js
We want to test both `record.get(key)` and `record.key` depending on the ember-data version one has.
=> Convert state tests to use native property access

addon/record-data.js, tests/unit/projections/writing-test.js
Projections and base models now have a synced up deleted state.
=> Sync projections and base model deleted state with CUSTOM_MODEL_CLASS

addon/base-record-array.js, addon/model.js, addon/services/m3-schema.js, addon/utils/is-m3-array.js, tests/integration/managed-array-tracked-test.js, tests/unit/record-array-test.js
The previous approach would result in apps breaking due to subtle differences in how ember entangles `[]` on template access vs us doing it in `objectAt`, `length` and `unknownProperty`.
This will be a breaking change for apps relying on `Array.isArray` returning false for m3 arrays. Using `addon/utils/is-m3-array.js` should enable those apps to migrate
=> Switch m3 array proxies to proxy [] insted of BaseRecordArray

addon/model.js, tests/unit/model/state-test.js
We were entangling `isDirty` by doing a `get(this, 'isDirty');` even when no one had read our dirty state. In some edge cases, this could result in rerendering errors, and was also not great for performance.
=> Do not needlessly access `isDirty`

m3-perf-testing-app/config/targets.js
We want to use a smallerr/faster build that does not include IE, as that is what most of our consumers will be doing
=> Do not target IE in the perf app

.github/workflows/ci.yml, addon/base-record-array.js, addon/utils/has-native-proxy.js, package.json, testem.js, tests/dummy/app/adapters/-json-api.js, tests/helpers/prop-get.js, tests/helpers/schema-versions.js, tests/integration/managed-array-tracked-test.js, tests/unit/model-test.js, tests/unit/model/native-access-arrays-test.js, tests/unit/model/native-access-test.js, tests/unit/model/state-test.js, yarn.lock
We were not testing against IE11, and a few failures had snuck in. We now only create m3 array proxies when we are able to instantiate a Proxy class, similarly to how Ember does it https://github.com/emberjs/ember.js/blob/v3.28.0/packages/@ember/-internals/utils/lib/proxy-utils.ts
=> Add IE testing and guard proxies when they are not present

addon/base-record-array.js, addon/managed-array.js
We don't need to have `_objects` be tracked because we manage notifications ourselves. Having `_objects` be an `Ember.A()` just ends up triggering change notifications that don't go anywhere.
=> Do not use an EmberArray for m3 array internal state

addon/record-data.js, addon/services/store.js, tests/unit/model-test.js
Speeds up test runs, and also makes app tests more robust against bad teardown states.
=> Do not emit array change events when app is being destroyed

.github/workflows/perf-check.yml
Recently, we discovered that the materialization perf scenario has had different results with CUSTOM_MODEL_CLASSES when run for a large number of items vs a small one. We now cover both cases.
=> Split materializing perf test into a large and a small one two

addon/model.js, addon/record-data.js, tests/unit/projections/common.js, tests/unit/projections/unloading-test.js, tests/unit/projections/writing-test.js, tests/unit/record-data-test.js
Building upon #1301, we now always keep record state flags on the `baseRecordData` and notify the record and projections when they change, having a unidirectional data flow. This is more robust, and fixes bugs where projections would get their state out of sync.
=> Unify `isDeleted`, `isNew` and `isDeletionCommitted` flag handling on Record Data

.github/workflows/ci.yml, package.json
Node v16 is It is moving from current to active on October 26, we should allow it so people can test their apps with the upcoming node LTS
=> Add support for Node v16

.github/workflows/ci.yml, addon/base-record-array.js, addon/model.js, package.json, tests/acceptance/m3-test.js, tests/integration/m3-debug-adapter-test.js, tests/interop/interop-debug-adapter-test.js, tests/unit/model-test.js, tests/unit/model/native-access-test.js, tests/unit/model/saving-test.js, tests/unit/schema-manager-test.js, tests/unit/utils/notify-changes-test.js
=> Fix property access in production and turn on prod testing

addon/model.js, package.json, tests/unit/model/native-access/native-access-arrays-test.js, tests/unit/model/native-access/native-access-test.js, tests/unit/model/native-access/tracked-properties-test.js, yarn.lock
The fix in https://github.com/hjdivad/ember-m3/pull/1376 was not correct. In order to properly entangle we need to be doing `receiver.get` but to protect against re-entrance in production, we need to manually keep track of the key being accessed.
=> Fix for tracked properties updating when using m3 native properties

.github/workflows/ci.yml, config/ember-try.js
- Builds on top of #1504 (to make rebasing easier and to see what is left)
- Use Ember 3.28 instead of `latest` in ember-try scenarios that are only trying to use a "recent" Ember version
- Update LTS / release try scenario versions (LTS => 3.28, LTS-1 => 3.24)
- Remove release-channel ember-try scenario (temporarily)
=> Update CI scenarios

package.json, yarn.lock
This package is no longer needed (hasn't been for quite a long time)
=> Remove ember-cli-shims

addon/model.js, tests/unit/model/errors-attribute-test.js
ensures that we have a setter for errors when using `useUnderylingErrorsValue`.
[fix #1533]
=> [bugfix] ensure that errors can be updated when using useUnderlyingErrorsValue

.github/workflows/ci.yml, .github/workflows/nightly.yml
We depend on the Ember Data CUSTOM_MODEL_CLASS feature flag, which is
off by default in 3.24.0, and on by default in 3.28.0. We used to have
to test this feature flag against canaries prior to 3.28.0's release,
but no longer.
We no longer depend on any optional feature flags, but still run the job
to ensure that enabling optional features in Ember Data does not
otherwise break ember-m3.
The job will be red right now because we currently are not compatible
with 4.0.0 and also not with canary releases of ember and ember-data.
Co-Authored-By: Larry Yu <laryu@linkedin.com>
=> Move feature-flags from CI to nightly

addon/model.js
in addition to symbols being very useful for stashing debug info, they error when you attempt to cast them to string for the deprecation.
=> Don't deprecate setting symbols

tests/unit/model/symbol-usage-test.js
[Fix #1569]
**Summary of change**
1. Added a test case to show how to use a symbol as an attribute name in emer-m3.
**Testing**
All test cases (yarn test) passed in local setup.
=> A test case to show how to use a symbol as an attribute name

addon/model.js
Addressing ember-inspector error when using [nativeProperties](https://github.com/hjdivad/ember-m3/blob/master/DEPRECATIONS.md#4x).
An example of the error:
```
2i6k580nwyl2cogqdnfyozj0i:19088 Uncaught Error: Cannot set a non-whitelisted property _oldWillDestroy on type FOO
at Proxy.setUnknownProperty (2i6k580nwyl2cogqdnfyozj0i:19088:63)
at Object.set (2i6k580nwyl2cogqdnfyozj0i:19029:99)
at e.retainObject (<anonymous>:4280:54)
at RenderTree._serializeObject (<anonymous>:2172:19)
at RenderTree._serializeItem (<anonymous>:2164:31)
at <anonymous>:2145:28
at Array.forEach (<anonymous>)
at RenderTree._serializeDict (<anonymous>:2144:25)
at RenderTree._serializeArgs (<anonymous>:2127:21)
at RenderTree._serializeRenderNode (<anonymous>:2112:22)
```
This issue is also mentioned here: …
=> Adding _oldWillDestroy to the prototype

.github/workflows/ci.yml
When a new commit is pushed to a branch/PR that already has a CI job running, the older (now outdated) CI job will be canceled. This frees up CI resources and allows the new commit's CI job to get started much sooner.
=> Cancel prior CI jobs for the same PR/branch.

addon/managed-array.js
Add `for` and `since` in deprecate() to be ember 4 compact 
- https://deprecations.emberjs.com/v3.x/#toc_ember-source-deprecation-without-for
- https://deprecations.emberjs.com/v3.x/#toc_ember-source-deprecation-without-since
=> [ember 4] Add `for` and `since` in deprecate() to be ember 4 compat

package.json
Per the README an active version of node is still required, but in
practice node versions don't break compatibility here.  Engine
restrictions can be added back if that ever changes.
=> Remove node engines restriction

addon/base-record-array.js, addon/model.js, addon/utils/notify-changes.js, package.json, tests/unit/model/reference-array-test.js, tests/unit/utils/notify-changes-test.js, yarn.lock
- Upgrade ember-source to 3.28.11
- Fix LinkTo deprecation
- Fix template deprecations
- Remove bowerrc
- Bump some deps
- jsconfig for LSP configuration
- v6 changelog
- Fix deprecations
- Upgrade to ember-source@4
- Notify array changes via `[]`
- Use notifyPropertyChange from @ember/object
- fixup notify array changes
- Replace arrayContentDidChange
- Test cleanup for readability
- Fix Ember.A clobbering
=> Update to ember-source@4

addon/base-record-array.js, tests/unit/model/native-access/native-access-surrogate-method-test.js
**Root Cause Analysis**
Ember 4.x replaced `arrayContentDidChange` with another function whereas the state of 'firstObject/lastObject' were left open.
**What has changed**
**Testing Done**
`yarn test` passed locally.
@co-authored-by [hjdivad](https://github.com/hjdivad)
=> Fix 'firstObject/lastObject' issue of BaseRecordArray caused by Ember 4.x

addon/record-data.js, tests/dummy/app/serializers/application.js, tests/unit/model/nested-merged-test.js
Nested models would not previously be merged under the following
conditions:
1. the nested models were projections of base models
2. the userland `computeBaseModelName` hook returned an undasherized
model name for nested models
This was due to a missing call to dasherize, to keep names normalized
for Ember Data.
=> Fix cache merging

addon/record-data.js, tests/dummy/app/serializers/application.js, tests/unit/model/nested-merged-test.js
Nested models would not previously be merged under the following
conditions:
1. the nested models were projections of base models
2. the userland `computeBaseModelName` hook returned an undasherized
model name for nested models
This was due to a missing call to dasherize, to keep names normalized
for Ember Data.
This re-applies #1733.
=> Fix nested cache merging for projections

addon/record-data.js, addon/services/store.js, tests/unit/record-data-test.js
Update embedded model creation to go via the store wrapper.
This allows downstreams to override `createNestedRecordData` in case they have any custom record data code.
=> feat: side-channel for nested record datas

addon/record-data.js, tests/unit/model/reuse-child-record-data-issue-test.js
When merging an update, if an existing M3RecordData object is reused, the corresponding `_data[key]` needs to be updated; otherwise, it'll cause the following issues:
1. When merging an update next time, the diffs will be incorrect.
2. When reading the updated attribute, _data[key] would return the stale value.
=> Fixed a gap in merging update

.github/workflows/ci.yml, .github/workflows/nightly.yml, ember-cli-build.js
1. Moved ember-latest to nightly
ember-latest tests against ember-source 5.x, which is NOT supported by ember-m3 yet
3. Removed test-ie
IE is no longer supported by the industry
=> chore: Updated CI

addon/record-data.js
**Summary**
1. Use base model name in comparison when getting existing child RecordData
**Testing**
`yarn test` passed locally
=> fix: use base model name for type comparison

addon/record-data.js
This reverts commit 5ee02bee7571d6d8b79fe96f2b5e3b7ff12785a4, reversing changes made to e3e72fc25621615ce16a2fe47c9fed50be9b28a6.
The use case was handled in its derived distribution, and hence the change is no longer needed for the time being.
=> Revert "Merge pull request #1750 from larry-x-yu/laryu/union-merge"

addon/initializers/m3-store.js, package.json
This silences the deprecation in apps running Ember 4.
https://deprecations.emberjs.com/v4.x/#toc_implicit-injections
For apps running Ember 4, this does nothing so is safe to remove
=> Remove Implicit Injections in m3-store

.github/workflows/ci.yml, config/ember-try.js, package.json, tests/interop/interop-debug-adapter-test.js, yarn.lock
* Bumps devDep for `ember-data`-related packages to `~4.4.0`
* Adds the following test scenarios and enables them in CI:
* ember-data-3-x-source-4-lts: This scenario maintains test compatibility between Ember-Data 3.28 and the latest Ember 4.x LTS version
* ember-data-3-x-source-4-8: For conservative compatibility, this maintains a similar scenario but against Ember 4.8
* ember-data-4-1: As the minimal viable upgrade for most apps coming from 3.28, this ensures compatibility with Ember-Data 4.1
* Minor: Bumps yarn to latest 1.x version in volta config
=> Ember-Data 4.4 Support
