- addon/query-cache.js
- tests/unit/query-cache-test.js
Not a new test, but update existing test to check against this particular failure scenario
> Add missing query cache test

- .eslintrc.js
- .gitignore
- .travis.yml
- config/ember-try.js
- ember-cli-build.js
- package.json
- tests/.eslintrc.js
- tests/dummy/app/app.js
- tests/dummy/app/index.html
- tests/dummy/config/environment.js
- tests/dummy/config/targets.js
- tests/helpers/module-for-acceptance.js
- tests/test-helper.js
- yarn.lock
Upgrades to the 2.15.1 blueprint.
> Upgrade addon blueprint

- addon/initializers/m3-store.js
- addon/model.js
- index.js
- package.json
- tests/dummy/app/initializers/schema-initializer.js
- tests/unit/model-test.js
- tests/unit/store-test.js
- yarn.lock
Depends on unreleased ember-data 2.17.0-beta.2 although the relevant
change can be monkeypatched if needed.
> Fix `peekRecord`, `peekAll`

- config/ember-try.js
- yarn.lock
> ember-try use yarn

- addon/initializers/m3-store.js
- addon/model.js
- addon/schema-manager.js
- tests/unit/projection-test.js
This PR requires #33 which it currently includes
> [FEAT] support for partially loaded state, findRecord/peekRecord/peekAll

- addon/model.js
- tests/unit/model-test.js
> Don't error on `nestedModel.unloadRecord()`

- tests/unit/projection-test.js
Requires PR #36.
This is an experiment to see what it will take to keep the delete states of a record in sync. It is missing the handling of the rollback.
Main concern is that it is quite elaborate and requires to duplicate a lot of the logic already existing in the state machine.  The alternative is to intercept `transitionTo` and invoke `transitionTo` on all related records if the state is a `deleted` substate. However, not sure how public this will be.
> [Projection Support] Tests for delete projections

- addon/model.js
- tests/unit/model-test.js
This is useful for
```
model.reload({ adapterOptions });
```
> Add options support to model.reload

- addon/initializers/m3-store.js
see https://github.com/hjdivad/ember-m3/pull/80#event-1467797580
> Clean up module-scoped init

- addon/model-data.js
- addon/model.js
- tests/unit/model-data-test.js
- tests/unit/model-test.js
> Fix eachAttribute to iterate over attributes

- CHANGELOG.md
- package.json
- tests/helpers/watch-property.js
- tests/test-helper.js
- tests/unit/projection-test.js
- yarn.lock
This is the projection test from #54 extracted in a standalone PR and all tests skipped.
> Projection support test only

- tests/unit/model-test.js
Add explicit test for setting a nested model (rather than mutating
fields within an existing nested model).
> Add test for changedAttributes

- addon/model-data.js
- addon/model.js
- addon/schema-manager.js
- tests/unit/model-data-test.js
- tests/unit/model-test.js
Updated logic to keep track of unknown keys getting resolved during resolve values.
> Updated logic to keep track of unknown keys getting resolved

- addon/model-data.js
- addon/model.js
- tests/unit/model-data-test.js
- tests/unit/projection-test.js
This is rebased and updated version of the #65 PR.
Couple of notes:
* Had to refactor how child model datas are created
* There is one missing test case for handling deletions because of updates.
> Projection support for embedded models

- CHANGELOG.md
- addon/query-cache.js
- tests/unit/query-cache-test.js
Extracted the serializer changes from #111
> Query url cache serializer

- addon/model.js
- tests/unit/model-test.js
Added Unit tests for above update and also M3RecordArray getter for `length` property.
> `setUnknownProperty` only update cache when value is resolved.

- addon/model.js
- tests/unit/model-test.js
And only update cache if value is resolved.
> `setUnknownProperty` remove cache after setting attribute.

- addon/model.js
- tests/unit/model-test.js
- Added unit tests for validation errors support in model
> Added support for validation errors in a record.

- README.md
- tests/unit/model-test.js
> [CHORE] adds guidance and a test for a common state book-keeping pitfall

- package.json
- yarn.lock
It's already transitive from ember-cli-pretender
> Remove pretender from devDeps

- app/services/m3-schema.js
- tests/unit/initializers/m3-store-test.js
- tests/unit/model-data-test.js
- tests/unit/model-test.js
- tests/unit/model/dependent-keys-test.js
- tests/unit/model/tracked-array-test.js
- tests/unit/query-cache-test.js
- tests/unit/store-test.js
User should extend DefaultSchema and export from app/services. Plus fix some sinon deprecation.
> Remove exporting m3-schema

- CHANGELOG.md
- package.json
- yarn.lock
Update to babel 7 should be a next major | minor bump
> rollback ember-cli-babel -> 6

- package.json
Reflecting the preferences people reported in #198.
> Updated contributor lines

- addon/record-data.js
- tests/unit/record-data-test.js
In order to be able to delete attributes through the schema we are making this public. 
cc @hjdivad
> Adds deleteAttr method to schema interface

- addon/record-array.js
- tests/unit/projection-test.js
also adds test for adding and then deleting a projection from a resolution array attached to a newly created parent projection
> [BUGFIX ReferenceArray.replace] fix error when replace is called without prototype extensions

- addon/record-data.js
- tests/unit/model/projections/changed-attrs-test.js
- tests/unit/record-data-test.js
We now have a fix for the issue this commit uncovered, so we should merge it back in
> Revert "Revert "Delegate `_destroyChildRecordData` to base""

- tests/unit/store-test.js
Currently "batching" only works for payloads that contain included
resources.  In principle it is easy to resolve if we flush in
`didSaveRecord` for payloads that do not contain included resources, but
there is no way for us to detect this and there isn't a method we can
override from ember data as this behaviour exists in a function within a
closure.
> chore: add tests for didSave

- addon/adapters/debug-adapter.js
- tests/integration/debug-adapter-test.js
Here are a couple of quick follow-up improvements for `debug-adapter`. Not sure if the test is what you had in mind based on your feedback (seems my test is causing me to stub out more, not less, out of necessity), but happy to refactor/re-write as needed.
> fix: stringify deeply nested data and minor refactoring in debug-adapter

- .travis.yml
- addon/-private.js
- addon/feature-flags.js
- addon/initializers/m3-store.js
- addon/m3-tracked-array.js
- addon/model.js
- addon/query-cache.js
- addon/record-array.js
- addon/record-data.js
- addon/resolve-attribute-util.js
- addon/utils/resolve.js
- tests/index.html
- tests/test-helper.js
- tests/unit/initializers/m3-store-test.js
- tests/unit/model-test.js
- tests/unit/model/changed-attrs-test.js
- tests/unit/model/projections/changed-attrs-test.js
- tests/unit/model/references-test.js
- tests/unit/model/state-test.js
- tests/unit/projection-test.js
- tests/unit/query-cache-test.js
- tests/unit/record-array-test.js
- tests/unit/record-data-test.js
- tests/unit/store/global-cache-test.js
- yarn.lock
To be ran together with https://github.com/emberjs/data/tree/igor/schema-temp 
The record arrays are backed by records right now, but no reason they can't be backed by record datas.
> custom record class m3 implementation

- addon/adapters/interop-debug-adapter.js
- tests/integration/interop-debug-adapter-test.js
> [BUGFIX] interop with newer ember-data

- package.json
- yarn.lock
> Revert "chore(deps-dev): bump ember-cli from 3.12.0 to 3.13.1"

- index.js
Import from ember-data for features was incorrect which failed once newest ED was published
> Fix canary feature imports

- .travis.yml
- README.md
- config/ember-try.js
Support + test release-1 as well as release (and lts, lts-1).
> Update support policy

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- bin/report-nightly-failure.js
> Improve Actions config

- .github/workflows/nightly.yml
- package.json
- yarn.lock
MVP so functionality is unchanged for this release.
> Switch to nyx

- .github/workflows/ci.yml
- config/ember-try.js
Closes https://github.com/hjdivad/ember-m3/issues/652
> Add ember-lts-3.16 ember-try scenario.

- README.md
- tests/dummy/app/routes/index.js
- tests/dummy/app/services/m3-schema.js
I had a hard time with hello world, the documented example just doesn't work. The tests/dummy does work, so this might save some time for someone
> updates readme with tests/dummy example and fix dummy

- addon/model.js
> Remove return in setter

- addon/m3-tracked-array.js
- addon/record-array.js
- addon/record-data.js
RecordArrays had leftover code from the array proxy days, which this
commit cleans up. Also adds feature flags in places where they were
missing
> cleanup: Cleanup and simplify RecordArray code

- addon/m3-tracked-array.js
- addon/record-array.js
- addon/resolve-attribute-util.js
I was hoping to not have to do this, as we will be dropping this code shortly
anyways, but it was blocking future refactors, and wasn't too much work
> TrackedArray and ReferenceArray inherit from same base class with ff off

- addon/base-record-array.js
- addon/managed-array.js
- addon/query-array.js
- addon/resolve-attribute-util.js
- tests/unit/model/changed-attrs-test.js
- tests/unit/model/reference-array-test.js
- tests/unit/model/tracked-array-test.js
- tests/unit/record-array-test.js
Also renames M3RecordArray to BaseRecordArray
> Rename RecordOwnedArray to ManagedArray fixes #792

- README.md
- addon/query-cache.js
- addon/utils/serialize-query-params.js
- tests/unit/query-cache-test.js
- tests/unit/utils/serialize-query-params-test.js
> Add queryParams option for Store.queryURL

- README.md
> Typo fix to README

- addon/record-data.js
- addon/services/store.js
> Drop use of Ember.merge

- CHANGELOG.md
- addon/adapters/interop-debug-adapter.js
- addon/record-data.js
- tests/unit/model/changed-attrs-test.js
PR to merge changes from PR#1031 for release/3-0-x branch
> feat: backport #1031 to 3.x

- .github/workflows/ci.yml
> CI node 13 -> 14

- .github/workflows/ci.yml
- tests/unit/model-test.js
> Remove CI usage of ember.js master channel

- addon/resolve-attribute-util.js
We were looking up the schemaType twice needlessly.
> Optimize schema types lookup

- addon/resolve-attribute-util.js
- tests/unit/model/tracked-array-test.js
This reverts the fix in https://github.com/hjdivad/ember-m3/pull/1167 in favor a more robust one. We can check whether we got a reference, pojo or an embedded record, and only dereference `_internalModel` for references. We only need to use it for references.
> Fix array resolving for non references when CUSTOM_MODEL_CLASS is off

- .github/workflows/ci.yml
- addon/model.js
- index.js
- tests/helpers/warning-handler.js
- tests/test-helper.js
- tests/unit/model-test.js
https://github.com/hjdivad/ember-m3/pull/1099
https://github.com/hjdivad/ember-m3/pull/1131
https://github.com/hjdivad/ember-m3/pull/1121
https://github.com/hjdivad/ember-m3/pull/1047
> Backport fixes to 3.x build: #1131 and #1121, bug: #1099 and test:#1047

- addon/model.js
Following the deprecation staging RFC https://github.com/emberjs/rfcs/pull/649
> Add 'for' and 'since' to nativeProperties deprecation

- .github/workflows/ci.yml
Don't rely on the default string setup
> Fix CI test name cosntruction

- addon/resolve-attribute-util.js
When creating a nested model, currently the framework determines whether to create a nested dirty model based on whether we are creating the model from a server payload. The check is not sufficient as in the case where a user might use model.set('nestedModelAttr', {...nestedModle}). The added check makes sure that this use case is covered when creating the nested model.
Testing done:
All test cases passed in local environment.
> Added more checks when creating nested model

- .github/workflows/ci.yml
- config/ember-try.js
- tests/interop/interop-debug-adapter-test.js
Attempt to fixup CI runs so that we can begin working on Ember 4 support.
> Fixup CI Runs

- package.json
- tests/dummy/config/optional-features.json
Not doing so is an error in Ember 4.0
> Set ember edition to "octane"

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- config/ember-try.js
depends-on
- #1708 
- #1711 
- #1710
> Update ember-try for 4.x

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- config/ember-try.js
- package.json
- yarn.lock
- Keep @ember-data packages in lockstep
- Update ember-try
> Update ember-try config

- .dependabot/config.yml
> Reduce dependabot clutter

- addon/initializers/m3-store.js
Fix a m3-store initialization issue.
`yarn test` passed locally.
> Fixed a m3-store initialization issue

- package.json
- yarn.lock
See https://deprecations.emberjs.com/id/ember-string-add-package
> add `@ember/string` to dependencies
